/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as ApiOgImageRouteImport } from './routes/api/og-image'
import { Route as LocaleSettingsRouteImport } from './routes/$locale/settings'
import { Route as LocalePackingListRouteImport } from './routes/$locale/packing-list'
import { Route as LocaleJetLagRouteImport } from './routes/$locale/jet-lag'
import { Route as LocaleCurrencyRouteImport } from './routes/$locale/currency'
import { Route as LocaleTravelPhrasesIndexRouteImport } from './routes/$locale/travel-phrases/index'
import { Route as LocaleLocalAppsIndexRouteImport } from './routes/$locale/local-apps/index'
import { Route as LocaleBillSplitterIndexRouteImport } from './routes/$locale/bill-splitter/index'
import { Route as ApiSiteHealthRouteImport } from './routes/api/site/health'
import { Route as ApiFxRatesRouteImport } from './routes/api/fx/rates'
import { Route as ApiFxDetectRouteImport } from './routes/api/fx/detect'
import { Route as LocaleTravelPhrasesCountryRouteImport } from './routes/$locale/travel-phrases/$country'
import { Route as LocaleLocalAppsCountryRouteImport } from './routes/$locale/local-apps/$country'
import { Route as LocaleBillSplitterTripIdRouteRouteImport } from './routes/$locale/bill-splitter/$tripId/route'
import { Route as ApiSplitBillTripsIndexRouteImport } from './routes/api/split-bill/trips/index'
import { Route as LocaleBillSplitterTripIdIndexRouteImport } from './routes/$locale/bill-splitter/$tripId/index'
import { Route as ApiSplitBillTripsTripIdRouteImport } from './routes/api/split-bill/trips/$tripId'
import { Route as ApiSplitBillDeviceBootstrapRouteImport } from './routes/api/split-bill/device/bootstrap'
import { Route as ApiPhraseAudioCountryPhraseIdRouteImport } from './routes/api/phrase-audio/$country/$phraseId'
import { Route as LocaleBillSplitterTripIdSettlementRouteImport } from './routes/$locale/bill-splitter/$tripId/settlement'
import { Route as LocaleBillSplitterTripIdAddRouteImport } from './routes/$locale/bill-splitter/$tripId/add'
import { Route as ApiSplitBillTripsTripIdSnapshotRouteImport } from './routes/api/split-bill/trips/$tripId/snapshot'
import { Route as ApiSplitBillTripsTripIdSettlementRouteImport } from './routes/api/split-bill/trips/$tripId/settlement'
import { Route as ApiSplitBillTripsTripIdSettingsRouteImport } from './routes/api/split-bill/trips/$tripId/settings'
import { Route as ApiSplitBillTripsTripIdImportRouteImport } from './routes/api/split-bill/trips/$tripId/import'
import { Route as ApiSplitBillTripsTripIdFxQuoteRouteImport } from './routes/api/split-bill/trips/$tripId/fx-quote'
import { Route as ApiSplitBillTripsTripIdExportRouteImport } from './routes/api/split-bill/trips/$tripId/export'
import { Route as ApiSplitBillTripsTripIdExpensesRouteImport } from './routes/api/split-bill/trips/$tripId/expenses'
import { Route as ApiSplitBillTripsTripIdExpensesExpenseIdRouteImport } from './routes/api/split-bill/trips/$tripId/expenses/$expenseId'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiOgImageRoute = ApiOgImageRouteImport.update({
  id: '/api/og-image',
  path: '/api/og-image',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSettingsRoute = LocaleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePackingListRoute = LocalePackingListRouteImport.update({
  id: '/packing-list',
  path: '/packing-list',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleJetLagRoute = LocaleJetLagRouteImport.update({
  id: '/jet-lag',
  path: '/jet-lag',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCurrencyRoute = LocaleCurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleTravelPhrasesIndexRoute =
  LocaleTravelPhrasesIndexRouteImport.update({
    id: '/travel-phrases/',
    path: '/travel-phrases/',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleLocalAppsIndexRoute = LocaleLocalAppsIndexRouteImport.update({
  id: '/local-apps/',
  path: '/local-apps/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBillSplitterIndexRoute = LocaleBillSplitterIndexRouteImport.update({
  id: '/bill-splitter/',
  path: '/bill-splitter/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const ApiSiteHealthRoute = ApiSiteHealthRouteImport.update({
  id: '/api/site/health',
  path: '/api/site/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxRatesRoute = ApiFxRatesRouteImport.update({
  id: '/api/fx/rates',
  path: '/api/fx/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFxDetectRoute = ApiFxDetectRouteImport.update({
  id: '/api/fx/detect',
  path: '/api/fx/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTravelPhrasesCountryRoute =
  LocaleTravelPhrasesCountryRouteImport.update({
    id: '/travel-phrases/$country',
    path: '/travel-phrases/$country',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleLocalAppsCountryRoute = LocaleLocalAppsCountryRouteImport.update({
  id: '/local-apps/$country',
  path: '/local-apps/$country',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleBillSplitterTripIdRouteRoute =
  LocaleBillSplitterTripIdRouteRouteImport.update({
    id: '/bill-splitter/$tripId',
    path: '/bill-splitter/$tripId',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const ApiSplitBillTripsIndexRoute = ApiSplitBillTripsIndexRouteImport.update({
  id: '/api/split-bill/trips/',
  path: '/api/split-bill/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleBillSplitterTripIdIndexRoute =
  LocaleBillSplitterTripIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LocaleBillSplitterTripIdRouteRoute,
  } as any)
const ApiSplitBillTripsTripIdRoute = ApiSplitBillTripsTripIdRouteImport.update({
  id: '/api/split-bill/trips/$tripId',
  path: '/api/split-bill/trips/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplitBillDeviceBootstrapRoute =
  ApiSplitBillDeviceBootstrapRouteImport.update({
    id: '/api/split-bill/device/bootstrap',
    path: '/api/split-bill/device/bootstrap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPhraseAudioCountryPhraseIdRoute =
  ApiPhraseAudioCountryPhraseIdRouteImport.update({
    id: '/api/phrase-audio/$country/$phraseId',
    path: '/api/phrase-audio/$country/$phraseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocaleBillSplitterTripIdSettlementRoute =
  LocaleBillSplitterTripIdSettlementRouteImport.update({
    id: '/settlement',
    path: '/settlement',
    getParentRoute: () => LocaleBillSplitterTripIdRouteRoute,
  } as any)
const LocaleBillSplitterTripIdAddRoute =
  LocaleBillSplitterTripIdAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => LocaleBillSplitterTripIdRouteRoute,
  } as any)
const ApiSplitBillTripsTripIdSnapshotRoute =
  ApiSplitBillTripsTripIdSnapshotRouteImport.update({
    id: '/snapshot',
    path: '/snapshot',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdSettlementRoute =
  ApiSplitBillTripsTripIdSettlementRouteImport.update({
    id: '/settlement',
    path: '/settlement',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdSettingsRoute =
  ApiSplitBillTripsTripIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdImportRoute =
  ApiSplitBillTripsTripIdImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdFxQuoteRoute =
  ApiSplitBillTripsTripIdFxQuoteRouteImport.update({
    id: '/fx-quote',
    path: '/fx-quote',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdExportRoute =
  ApiSplitBillTripsTripIdExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdExpensesRoute =
  ApiSplitBillTripsTripIdExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => ApiSplitBillTripsTripIdRoute,
  } as any)
const ApiSplitBillTripsTripIdExpensesExpenseIdRoute =
  ApiSplitBillTripsTripIdExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => ApiSplitBillTripsTripIdExpensesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/currency': typeof LocaleCurrencyRoute
  '/$locale/jet-lag': typeof LocaleJetLagRoute
  '/$locale/packing-list': typeof LocalePackingListRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/bill-splitter/$tripId': typeof LocaleBillSplitterTripIdRouteRouteWithChildren
  '/$locale/local-apps/$country': typeof LocaleLocalAppsCountryRoute
  '/$locale/travel-phrases/$country': typeof LocaleTravelPhrasesCountryRoute
  '/api/fx/detect': typeof ApiFxDetectRoute
  '/api/fx/rates': typeof ApiFxRatesRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/$locale/bill-splitter/': typeof LocaleBillSplitterIndexRoute
  '/$locale/local-apps/': typeof LocaleLocalAppsIndexRoute
  '/$locale/travel-phrases/': typeof LocaleTravelPhrasesIndexRoute
  '/$locale/bill-splitter/$tripId/add': typeof LocaleBillSplitterTripIdAddRoute
  '/$locale/bill-splitter/$tripId/settlement': typeof LocaleBillSplitterTripIdSettlementRoute
  '/api/phrase-audio/$country/$phraseId': typeof ApiPhraseAudioCountryPhraseIdRoute
  '/api/split-bill/device/bootstrap': typeof ApiSplitBillDeviceBootstrapRoute
  '/api/split-bill/trips/$tripId': typeof ApiSplitBillTripsTripIdRouteWithChildren
  '/$locale/bill-splitter/$tripId/': typeof LocaleBillSplitterTripIdIndexRoute
  '/api/split-bill/trips/': typeof ApiSplitBillTripsIndexRoute
  '/api/split-bill/trips/$tripId/expenses': typeof ApiSplitBillTripsTripIdExpensesRouteWithChildren
  '/api/split-bill/trips/$tripId/export': typeof ApiSplitBillTripsTripIdExportRoute
  '/api/split-bill/trips/$tripId/fx-quote': typeof ApiSplitBillTripsTripIdFxQuoteRoute
  '/api/split-bill/trips/$tripId/import': typeof ApiSplitBillTripsTripIdImportRoute
  '/api/split-bill/trips/$tripId/settings': typeof ApiSplitBillTripsTripIdSettingsRoute
  '/api/split-bill/trips/$tripId/settlement': typeof ApiSplitBillTripsTripIdSettlementRoute
  '/api/split-bill/trips/$tripId/snapshot': typeof ApiSplitBillTripsTripIdSnapshotRoute
  '/api/split-bill/trips/$tripId/expenses/$expenseId': typeof ApiSplitBillTripsTripIdExpensesExpenseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/currency': typeof LocaleCurrencyRoute
  '/$locale/jet-lag': typeof LocaleJetLagRoute
  '/$locale/packing-list': typeof LocalePackingListRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/local-apps/$country': typeof LocaleLocalAppsCountryRoute
  '/$locale/travel-phrases/$country': typeof LocaleTravelPhrasesCountryRoute
  '/api/fx/detect': typeof ApiFxDetectRoute
  '/api/fx/rates': typeof ApiFxRatesRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/$locale/bill-splitter': typeof LocaleBillSplitterIndexRoute
  '/$locale/local-apps': typeof LocaleLocalAppsIndexRoute
  '/$locale/travel-phrases': typeof LocaleTravelPhrasesIndexRoute
  '/$locale/bill-splitter/$tripId/add': typeof LocaleBillSplitterTripIdAddRoute
  '/$locale/bill-splitter/$tripId/settlement': typeof LocaleBillSplitterTripIdSettlementRoute
  '/api/phrase-audio/$country/$phraseId': typeof ApiPhraseAudioCountryPhraseIdRoute
  '/api/split-bill/device/bootstrap': typeof ApiSplitBillDeviceBootstrapRoute
  '/api/split-bill/trips/$tripId': typeof ApiSplitBillTripsTripIdRouteWithChildren
  '/$locale/bill-splitter/$tripId': typeof LocaleBillSplitterTripIdIndexRoute
  '/api/split-bill/trips': typeof ApiSplitBillTripsIndexRoute
  '/api/split-bill/trips/$tripId/expenses': typeof ApiSplitBillTripsTripIdExpensesRouteWithChildren
  '/api/split-bill/trips/$tripId/export': typeof ApiSplitBillTripsTripIdExportRoute
  '/api/split-bill/trips/$tripId/fx-quote': typeof ApiSplitBillTripsTripIdFxQuoteRoute
  '/api/split-bill/trips/$tripId/import': typeof ApiSplitBillTripsTripIdImportRoute
  '/api/split-bill/trips/$tripId/settings': typeof ApiSplitBillTripsTripIdSettingsRoute
  '/api/split-bill/trips/$tripId/settlement': typeof ApiSplitBillTripsTripIdSettlementRoute
  '/api/split-bill/trips/$tripId/snapshot': typeof ApiSplitBillTripsTripIdSnapshotRoute
  '/api/split-bill/trips/$tripId/expenses/$expenseId': typeof ApiSplitBillTripsTripIdExpensesExpenseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/currency': typeof LocaleCurrencyRoute
  '/$locale/jet-lag': typeof LocaleJetLagRoute
  '/$locale/packing-list': typeof LocalePackingListRoute
  '/$locale/settings': typeof LocaleSettingsRoute
  '/api/og-image': typeof ApiOgImageRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/bill-splitter/$tripId': typeof LocaleBillSplitterTripIdRouteRouteWithChildren
  '/$locale/local-apps/$country': typeof LocaleLocalAppsCountryRoute
  '/$locale/travel-phrases/$country': typeof LocaleTravelPhrasesCountryRoute
  '/api/fx/detect': typeof ApiFxDetectRoute
  '/api/fx/rates': typeof ApiFxRatesRoute
  '/api/site/health': typeof ApiSiteHealthRoute
  '/$locale/bill-splitter/': typeof LocaleBillSplitterIndexRoute
  '/$locale/local-apps/': typeof LocaleLocalAppsIndexRoute
  '/$locale/travel-phrases/': typeof LocaleTravelPhrasesIndexRoute
  '/$locale/bill-splitter/$tripId/add': typeof LocaleBillSplitterTripIdAddRoute
  '/$locale/bill-splitter/$tripId/settlement': typeof LocaleBillSplitterTripIdSettlementRoute
  '/api/phrase-audio/$country/$phraseId': typeof ApiPhraseAudioCountryPhraseIdRoute
  '/api/split-bill/device/bootstrap': typeof ApiSplitBillDeviceBootstrapRoute
  '/api/split-bill/trips/$tripId': typeof ApiSplitBillTripsTripIdRouteWithChildren
  '/$locale/bill-splitter/$tripId/': typeof LocaleBillSplitterTripIdIndexRoute
  '/api/split-bill/trips/': typeof ApiSplitBillTripsIndexRoute
  '/api/split-bill/trips/$tripId/expenses': typeof ApiSplitBillTripsTripIdExpensesRouteWithChildren
  '/api/split-bill/trips/$tripId/export': typeof ApiSplitBillTripsTripIdExportRoute
  '/api/split-bill/trips/$tripId/fx-quote': typeof ApiSplitBillTripsTripIdFxQuoteRoute
  '/api/split-bill/trips/$tripId/import': typeof ApiSplitBillTripsTripIdImportRoute
  '/api/split-bill/trips/$tripId/settings': typeof ApiSplitBillTripsTripIdSettingsRoute
  '/api/split-bill/trips/$tripId/settlement': typeof ApiSplitBillTripsTripIdSettlementRoute
  '/api/split-bill/trips/$tripId/snapshot': typeof ApiSplitBillTripsTripIdSnapshotRoute
  '/api/split-bill/trips/$tripId/expenses/$expenseId': typeof ApiSplitBillTripsTripIdExpensesExpenseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/currency'
    | '/$locale/jet-lag'
    | '/$locale/packing-list'
    | '/$locale/settings'
    | '/api/og-image'
    | '/$locale/'
    | '/$locale/bill-splitter/$tripId'
    | '/$locale/local-apps/$country'
    | '/$locale/travel-phrases/$country'
    | '/api/fx/detect'
    | '/api/fx/rates'
    | '/api/site/health'
    | '/$locale/bill-splitter/'
    | '/$locale/local-apps/'
    | '/$locale/travel-phrases/'
    | '/$locale/bill-splitter/$tripId/add'
    | '/$locale/bill-splitter/$tripId/settlement'
    | '/api/phrase-audio/$country/$phraseId'
    | '/api/split-bill/device/bootstrap'
    | '/api/split-bill/trips/$tripId'
    | '/$locale/bill-splitter/$tripId/'
    | '/api/split-bill/trips/'
    | '/api/split-bill/trips/$tripId/expenses'
    | '/api/split-bill/trips/$tripId/export'
    | '/api/split-bill/trips/$tripId/fx-quote'
    | '/api/split-bill/trips/$tripId/import'
    | '/api/split-bill/trips/$tripId/settings'
    | '/api/split-bill/trips/$tripId/settlement'
    | '/api/split-bill/trips/$tripId/snapshot'
    | '/api/split-bill/trips/$tripId/expenses/$expenseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/currency'
    | '/$locale/jet-lag'
    | '/$locale/packing-list'
    | '/$locale/settings'
    | '/api/og-image'
    | '/$locale'
    | '/$locale/local-apps/$country'
    | '/$locale/travel-phrases/$country'
    | '/api/fx/detect'
    | '/api/fx/rates'
    | '/api/site/health'
    | '/$locale/bill-splitter'
    | '/$locale/local-apps'
    | '/$locale/travel-phrases'
    | '/$locale/bill-splitter/$tripId/add'
    | '/$locale/bill-splitter/$tripId/settlement'
    | '/api/phrase-audio/$country/$phraseId'
    | '/api/split-bill/device/bootstrap'
    | '/api/split-bill/trips/$tripId'
    | '/$locale/bill-splitter/$tripId'
    | '/api/split-bill/trips'
    | '/api/split-bill/trips/$tripId/expenses'
    | '/api/split-bill/trips/$tripId/export'
    | '/api/split-bill/trips/$tripId/fx-quote'
    | '/api/split-bill/trips/$tripId/import'
    | '/api/split-bill/trips/$tripId/settings'
    | '/api/split-bill/trips/$tripId/settlement'
    | '/api/split-bill/trips/$tripId/snapshot'
    | '/api/split-bill/trips/$tripId/expenses/$expenseId'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/currency'
    | '/$locale/jet-lag'
    | '/$locale/packing-list'
    | '/$locale/settings'
    | '/api/og-image'
    | '/$locale/'
    | '/$locale/bill-splitter/$tripId'
    | '/$locale/local-apps/$country'
    | '/$locale/travel-phrases/$country'
    | '/api/fx/detect'
    | '/api/fx/rates'
    | '/api/site/health'
    | '/$locale/bill-splitter/'
    | '/$locale/local-apps/'
    | '/$locale/travel-phrases/'
    | '/$locale/bill-splitter/$tripId/add'
    | '/$locale/bill-splitter/$tripId/settlement'
    | '/api/phrase-audio/$country/$phraseId'
    | '/api/split-bill/device/bootstrap'
    | '/api/split-bill/trips/$tripId'
    | '/$locale/bill-splitter/$tripId/'
    | '/api/split-bill/trips/'
    | '/api/split-bill/trips/$tripId/expenses'
    | '/api/split-bill/trips/$tripId/export'
    | '/api/split-bill/trips/$tripId/fx-quote'
    | '/api/split-bill/trips/$tripId/import'
    | '/api/split-bill/trips/$tripId/settings'
    | '/api/split-bill/trips/$tripId/settlement'
    | '/api/split-bill/trips/$tripId/snapshot'
    | '/api/split-bill/trips/$tripId/expenses/$expenseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  ApiOgImageRoute: typeof ApiOgImageRoute
  ApiFxDetectRoute: typeof ApiFxDetectRoute
  ApiFxRatesRoute: typeof ApiFxRatesRoute
  ApiSiteHealthRoute: typeof ApiSiteHealthRoute
  ApiPhraseAudioCountryPhraseIdRoute: typeof ApiPhraseAudioCountryPhraseIdRoute
  ApiSplitBillDeviceBootstrapRoute: typeof ApiSplitBillDeviceBootstrapRoute
  ApiSplitBillTripsTripIdRoute: typeof ApiSplitBillTripsTripIdRouteWithChildren
  ApiSplitBillTripsIndexRoute: typeof ApiSplitBillTripsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/og-image': {
      id: '/api/og-image'
      path: '/api/og-image'
      fullPath: '/api/og-image'
      preLoaderRoute: typeof ApiOgImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/settings': {
      id: '/$locale/settings'
      path: '/settings'
      fullPath: '/$locale/settings'
      preLoaderRoute: typeof LocaleSettingsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/packing-list': {
      id: '/$locale/packing-list'
      path: '/packing-list'
      fullPath: '/$locale/packing-list'
      preLoaderRoute: typeof LocalePackingListRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/jet-lag': {
      id: '/$locale/jet-lag'
      path: '/jet-lag'
      fullPath: '/$locale/jet-lag'
      preLoaderRoute: typeof LocaleJetLagRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/currency': {
      id: '/$locale/currency'
      path: '/currency'
      fullPath: '/$locale/currency'
      preLoaderRoute: typeof LocaleCurrencyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/travel-phrases/': {
      id: '/$locale/travel-phrases/'
      path: '/travel-phrases'
      fullPath: '/$locale/travel-phrases/'
      preLoaderRoute: typeof LocaleTravelPhrasesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/local-apps/': {
      id: '/$locale/local-apps/'
      path: '/local-apps'
      fullPath: '/$locale/local-apps/'
      preLoaderRoute: typeof LocaleLocalAppsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/bill-splitter/': {
      id: '/$locale/bill-splitter/'
      path: '/bill-splitter'
      fullPath: '/$locale/bill-splitter/'
      preLoaderRoute: typeof LocaleBillSplitterIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/site/health': {
      id: '/api/site/health'
      path: '/api/site/health'
      fullPath: '/api/site/health'
      preLoaderRoute: typeof ApiSiteHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx/rates': {
      id: '/api/fx/rates'
      path: '/api/fx/rates'
      fullPath: '/api/fx/rates'
      preLoaderRoute: typeof ApiFxRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fx/detect': {
      id: '/api/fx/detect'
      path: '/api/fx/detect'
      fullPath: '/api/fx/detect'
      preLoaderRoute: typeof ApiFxDetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/travel-phrases/$country': {
      id: '/$locale/travel-phrases/$country'
      path: '/travel-phrases/$country'
      fullPath: '/$locale/travel-phrases/$country'
      preLoaderRoute: typeof LocaleTravelPhrasesCountryRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/local-apps/$country': {
      id: '/$locale/local-apps/$country'
      path: '/local-apps/$country'
      fullPath: '/$locale/local-apps/$country'
      preLoaderRoute: typeof LocaleLocalAppsCountryRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/bill-splitter/$tripId': {
      id: '/$locale/bill-splitter/$tripId'
      path: '/bill-splitter/$tripId'
      fullPath: '/$locale/bill-splitter/$tripId'
      preLoaderRoute: typeof LocaleBillSplitterTripIdRouteRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/api/split-bill/trips/': {
      id: '/api/split-bill/trips/'
      path: '/api/split-bill/trips'
      fullPath: '/api/split-bill/trips/'
      preLoaderRoute: typeof ApiSplitBillTripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/bill-splitter/$tripId/': {
      id: '/$locale/bill-splitter/$tripId/'
      path: '/'
      fullPath: '/$locale/bill-splitter/$tripId/'
      preLoaderRoute: typeof LocaleBillSplitterTripIdIndexRouteImport
      parentRoute: typeof LocaleBillSplitterTripIdRouteRoute
    }
    '/api/split-bill/trips/$tripId': {
      id: '/api/split-bill/trips/$tripId'
      path: '/api/split-bill/trips/$tripId'
      fullPath: '/api/split-bill/trips/$tripId'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/split-bill/device/bootstrap': {
      id: '/api/split-bill/device/bootstrap'
      path: '/api/split-bill/device/bootstrap'
      fullPath: '/api/split-bill/device/bootstrap'
      preLoaderRoute: typeof ApiSplitBillDeviceBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/phrase-audio/$country/$phraseId': {
      id: '/api/phrase-audio/$country/$phraseId'
      path: '/api/phrase-audio/$country/$phraseId'
      fullPath: '/api/phrase-audio/$country/$phraseId'
      preLoaderRoute: typeof ApiPhraseAudioCountryPhraseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/bill-splitter/$tripId/settlement': {
      id: '/$locale/bill-splitter/$tripId/settlement'
      path: '/settlement'
      fullPath: '/$locale/bill-splitter/$tripId/settlement'
      preLoaderRoute: typeof LocaleBillSplitterTripIdSettlementRouteImport
      parentRoute: typeof LocaleBillSplitterTripIdRouteRoute
    }
    '/$locale/bill-splitter/$tripId/add': {
      id: '/$locale/bill-splitter/$tripId/add'
      path: '/add'
      fullPath: '/$locale/bill-splitter/$tripId/add'
      preLoaderRoute: typeof LocaleBillSplitterTripIdAddRouteImport
      parentRoute: typeof LocaleBillSplitterTripIdRouteRoute
    }
    '/api/split-bill/trips/$tripId/snapshot': {
      id: '/api/split-bill/trips/$tripId/snapshot'
      path: '/snapshot'
      fullPath: '/api/split-bill/trips/$tripId/snapshot'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdSnapshotRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/settlement': {
      id: '/api/split-bill/trips/$tripId/settlement'
      path: '/settlement'
      fullPath: '/api/split-bill/trips/$tripId/settlement'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdSettlementRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/settings': {
      id: '/api/split-bill/trips/$tripId/settings'
      path: '/settings'
      fullPath: '/api/split-bill/trips/$tripId/settings'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdSettingsRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/import': {
      id: '/api/split-bill/trips/$tripId/import'
      path: '/import'
      fullPath: '/api/split-bill/trips/$tripId/import'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdImportRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/fx-quote': {
      id: '/api/split-bill/trips/$tripId/fx-quote'
      path: '/fx-quote'
      fullPath: '/api/split-bill/trips/$tripId/fx-quote'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdFxQuoteRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/export': {
      id: '/api/split-bill/trips/$tripId/export'
      path: '/export'
      fullPath: '/api/split-bill/trips/$tripId/export'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdExportRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/expenses': {
      id: '/api/split-bill/trips/$tripId/expenses'
      path: '/expenses'
      fullPath: '/api/split-bill/trips/$tripId/expenses'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdExpensesRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdRoute
    }
    '/api/split-bill/trips/$tripId/expenses/$expenseId': {
      id: '/api/split-bill/trips/$tripId/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/api/split-bill/trips/$tripId/expenses/$expenseId'
      preLoaderRoute: typeof ApiSplitBillTripsTripIdExpensesExpenseIdRouteImport
      parentRoute: typeof ApiSplitBillTripsTripIdExpensesRoute
    }
  }
}

interface LocaleBillSplitterTripIdRouteRouteChildren {
  LocaleBillSplitterTripIdAddRoute: typeof LocaleBillSplitterTripIdAddRoute
  LocaleBillSplitterTripIdSettlementRoute: typeof LocaleBillSplitterTripIdSettlementRoute
  LocaleBillSplitterTripIdIndexRoute: typeof LocaleBillSplitterTripIdIndexRoute
}

const LocaleBillSplitterTripIdRouteRouteChildren: LocaleBillSplitterTripIdRouteRouteChildren =
  {
    LocaleBillSplitterTripIdAddRoute: LocaleBillSplitterTripIdAddRoute,
    LocaleBillSplitterTripIdSettlementRoute:
      LocaleBillSplitterTripIdSettlementRoute,
    LocaleBillSplitterTripIdIndexRoute: LocaleBillSplitterTripIdIndexRoute,
  }

const LocaleBillSplitterTripIdRouteRouteWithChildren =
  LocaleBillSplitterTripIdRouteRoute._addFileChildren(
    LocaleBillSplitterTripIdRouteRouteChildren,
  )

interface LocaleRouteRouteChildren {
  LocaleCurrencyRoute: typeof LocaleCurrencyRoute
  LocaleJetLagRoute: typeof LocaleJetLagRoute
  LocalePackingListRoute: typeof LocalePackingListRoute
  LocaleSettingsRoute: typeof LocaleSettingsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBillSplitterTripIdRouteRoute: typeof LocaleBillSplitterTripIdRouteRouteWithChildren
  LocaleLocalAppsCountryRoute: typeof LocaleLocalAppsCountryRoute
  LocaleTravelPhrasesCountryRoute: typeof LocaleTravelPhrasesCountryRoute
  LocaleBillSplitterIndexRoute: typeof LocaleBillSplitterIndexRoute
  LocaleLocalAppsIndexRoute: typeof LocaleLocalAppsIndexRoute
  LocaleTravelPhrasesIndexRoute: typeof LocaleTravelPhrasesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleCurrencyRoute: LocaleCurrencyRoute,
  LocaleJetLagRoute: LocaleJetLagRoute,
  LocalePackingListRoute: LocalePackingListRoute,
  LocaleSettingsRoute: LocaleSettingsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBillSplitterTripIdRouteRoute:
    LocaleBillSplitterTripIdRouteRouteWithChildren,
  LocaleLocalAppsCountryRoute: LocaleLocalAppsCountryRoute,
  LocaleTravelPhrasesCountryRoute: LocaleTravelPhrasesCountryRoute,
  LocaleBillSplitterIndexRoute: LocaleBillSplitterIndexRoute,
  LocaleLocalAppsIndexRoute: LocaleLocalAppsIndexRoute,
  LocaleTravelPhrasesIndexRoute: LocaleTravelPhrasesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface ApiSplitBillTripsTripIdExpensesRouteChildren {
  ApiSplitBillTripsTripIdExpensesExpenseIdRoute: typeof ApiSplitBillTripsTripIdExpensesExpenseIdRoute
}

const ApiSplitBillTripsTripIdExpensesRouteChildren: ApiSplitBillTripsTripIdExpensesRouteChildren =
  {
    ApiSplitBillTripsTripIdExpensesExpenseIdRoute:
      ApiSplitBillTripsTripIdExpensesExpenseIdRoute,
  }

const ApiSplitBillTripsTripIdExpensesRouteWithChildren =
  ApiSplitBillTripsTripIdExpensesRoute._addFileChildren(
    ApiSplitBillTripsTripIdExpensesRouteChildren,
  )

interface ApiSplitBillTripsTripIdRouteChildren {
  ApiSplitBillTripsTripIdExpensesRoute: typeof ApiSplitBillTripsTripIdExpensesRouteWithChildren
  ApiSplitBillTripsTripIdExportRoute: typeof ApiSplitBillTripsTripIdExportRoute
  ApiSplitBillTripsTripIdFxQuoteRoute: typeof ApiSplitBillTripsTripIdFxQuoteRoute
  ApiSplitBillTripsTripIdImportRoute: typeof ApiSplitBillTripsTripIdImportRoute
  ApiSplitBillTripsTripIdSettingsRoute: typeof ApiSplitBillTripsTripIdSettingsRoute
  ApiSplitBillTripsTripIdSettlementRoute: typeof ApiSplitBillTripsTripIdSettlementRoute
  ApiSplitBillTripsTripIdSnapshotRoute: typeof ApiSplitBillTripsTripIdSnapshotRoute
}

const ApiSplitBillTripsTripIdRouteChildren: ApiSplitBillTripsTripIdRouteChildren =
  {
    ApiSplitBillTripsTripIdExpensesRoute:
      ApiSplitBillTripsTripIdExpensesRouteWithChildren,
    ApiSplitBillTripsTripIdExportRoute: ApiSplitBillTripsTripIdExportRoute,
    ApiSplitBillTripsTripIdFxQuoteRoute: ApiSplitBillTripsTripIdFxQuoteRoute,
    ApiSplitBillTripsTripIdImportRoute: ApiSplitBillTripsTripIdImportRoute,
    ApiSplitBillTripsTripIdSettingsRoute: ApiSplitBillTripsTripIdSettingsRoute,
    ApiSplitBillTripsTripIdSettlementRoute:
      ApiSplitBillTripsTripIdSettlementRoute,
    ApiSplitBillTripsTripIdSnapshotRoute: ApiSplitBillTripsTripIdSnapshotRoute,
  }

const ApiSplitBillTripsTripIdRouteWithChildren =
  ApiSplitBillTripsTripIdRoute._addFileChildren(
    ApiSplitBillTripsTripIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ApiOgImageRoute: ApiOgImageRoute,
  ApiFxDetectRoute: ApiFxDetectRoute,
  ApiFxRatesRoute: ApiFxRatesRoute,
  ApiSiteHealthRoute: ApiSiteHealthRoute,
  ApiPhraseAudioCountryPhraseIdRoute: ApiPhraseAudioCountryPhraseIdRoute,
  ApiSplitBillDeviceBootstrapRoute: ApiSplitBillDeviceBootstrapRoute,
  ApiSplitBillTripsTripIdRoute: ApiSplitBillTripsTripIdRouteWithChildren,
  ApiSplitBillTripsIndexRoute: ApiSplitBillTripsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
